### ISSUE TITLE
hardened energy upgrade not adding

### ISSUE THREAD

**Issue by wimvanboven** [chbachman/ModularArmour#60]
when adding the hardened energy upgrade (4 lapis, lapis block, 4 redstone) using 1.0.15-38 build, pressing the ok button does nothing. the gui updates and indicates it recognizes the recipe, though.

adding leadstone energy upgrade does work.

**Comment by chbachman** [comment]
Okay, I see the issue.

The hardened energy upgrade depends on the leadstone energy upgrade.

I thought I was indicating this, but it turns out that I am not.

However, I am adding a method to indicate this in the future (e.g. the next feature) so this indication will be fixed.
