### ISSUE TITLE
Suggestion: MPS/Simply Jetpacks style flight

### ISSUE THREAD

**Issue by NullMagic** [chbachman/ModularArmour#68]
So, one of the things that I really liked about Modular Power Suits was the way flight worked, when I had the jetpack installed instead of just putting me into creative flight mode it allowed me to hold down space and fly, and of course if you didn't have the Flight Control upgrade you stopped flying while holding space, you could also fly in whatever direction you were looking, going up, down, left, right etc, instead of requiring the space bar or descent key once the control was installed.

Anyway, with the exposition out of the way, that's something I'd like to see in this mod, other than that, I think you're doing a great job! Keep it up!

**Comment by chbachman** [comment]
That's something I have wanted for a while as well, and I'll push it with the 1.2 update if all goes well.

**Comment by NullMagic** [comment]
Awesome!  I'm glad to hear that, and really look forward to future updates!
