### ISSUE TITLE
Crash to desktop after installing 1.0.17-40

### ISSUE THREAD

**Issue by ChrispyBites** [chbachman/ModularArmour#69]
I just added the newest version to FTB Horizon's Daybreaker, got the following crash while loading mods:

http://pastebin.com/HaXes4Kq

Thanks!

**Comment by chbachman** [comment]
Quick fix, I'll take a look

**Comment by ChrispyBites** [comment]
Awesome, thanks for checking it out.  Also, great mod, a billion times less complicated than that other one.

**Comment by ChrispyBites** [comment]
Quick question... how does the potion upgrade work?  I don't see any additional GUI options.

**Comment by chbachman** [comment]
It allows the night vision and invisibility to work

**Comment by chbachman** [comment]
Update CoFH Core to 3.0.3 and recheck
