### ISSUE TITLE
Couldn't Render Entity NPE

### ISSUE THREAD

**Issue by TycoonGT** [chbachman/ModularArmour#70]
I added your mod to my custom modpack and have come across a bug that causes the following error to appear in the console every second, it also causes the game to lag out severely:

http://pastebin.com/Z1beTLts

The error appears whether I am wearing the armor or I am looking at another player wearing the armor. While equipped, it also makes any other armor the player is wearing have no appearance.

This is a list of mods I currently have installed: http://pastebin.com/K886JpT1

I am not sure if this is the right process I need to take, this is my first Issue Request.

Thanks

**Comment by chbachman** [comment]
Could you give me the whole log?

**Comment by TycoonGT** [comment]
Sorry I have not responded earlier, I was busy with RL. 

http://www.megafileupload.com/dgUz/modular_armor_log_file.zip

Log file too big for pastebin.

**Comment by TycoonGT** [comment]
I think issue #72 is related to the problem I am experiencing.

**Comment by HowardRoark2016** [comment]
I appear to have the same issue. You might remember me from the closed Issue #66. I have upgraded from the 1.0.2 version of FtB Horizons: Daybreaker to the 1.1.0 version. Like AngeldelaMuerte mentioned in the OP of Issue #72, I am also seeing my normal skin when I open my inventory and not the texture of the Modular armor (Modular helmet, leggings, and boots). I am getting this text spammed constantly in the console window and it is causing a severe drop in FPS - http://pastebin.com/AKaPpYgz

Here is the entire console window log - http://www.megafileupload.com/9571/ftb-horizons-daybreaker-1.1-logs.zip

I am playing FtB Horizons: Daybreaker v1.1 and using ModularArmour-1.7.10-1.0.17-40.jar and CoFHCore-[1.7.10]3.0.3-303.jar.

**Comment by chbachman** [comment]
Check with the newest version.

**Comment by chbachman** [comment]
I'm going to close this until I get confirmation that it is still happening with the latest version.
