### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by Brigy** [chbachman/ModularArmour#71]
Just installed ModularArmour-1.7.10-1.0.17-40 on a FTB Infinity server.

Game crashes repeatedly when opening the armour GUI.

Here is the crash report, wondered if you could take a look as I know nothing about troubleshooting.

http://pastebin.com/S8BkK9M5

**Comment by chbachman** [comment]
Update Cofh core to 3.0.3

**Comment by Brigy** [comment]
Thank you very much, very fast response appreciated :D
