### ISSUE TITLE
Adding an upgrade makes armor textures disappear

### ISSUE THREAD

**Issue by AngeldelaMuerte** [chbachman/ModularArmour#72]
I'm using Modular Armor 1.0.17-40 and CoFH 303. I can make the full set of armor fine and the GUI works great, I've installed the new textures to try them out and they work great.

However, whenever I install an upgrade (the ones I've tried so far are hardened energy and general protector) when I put the armor back on, there are no textures and all I see is my player skin. The game still recognises that I'm wearing the armor as there is a little GUI off the side of the screen that shows the armor with it's durability and such (I think it might be part of Ars Magica 2).

I know there's an upgrade which has making the armor disappear as it's primary function but I didn't install that one. As far as I'm aware this isn't causing the armor to not work, it's just annoying because I think the armor textures are cool.
![2015-07-30_17 03 20](https://cloud.githubusercontent.com/assets/13567193/8977474/f6edf5a8-36dc-11e5-8b02-a18125ec20b0.png)
![2015-07-30_17 03 33](https://cloud.githubusercontent.com/assets/13567193/8977475/f6ef32a6-36dc-11e5-9326-294b0ebbf2bf.png)

**Comment by chbachman** [comment]
No longer being updated, sorry. Check the Readme for information.
