### ISSUE TITLE
Intermittent fatal error

### ISSUE THREAD

**Issue by devryb** [chbachman/ModularArmour#74]
Sometimes when applying upgrades to armor players are kicked with "A fatal error has occured, this connection is terminated"

This error is displayed in the server log:
http://pastebin.com/kxEHCxFt

**Comment by chbachman** [comment]
Update CoFH Core

**Comment by burglarnoone** [comment]
Hi getting the same thing as OP, when applying armour upgrades on the server players get kicked. Using forge 10.13.4.1448 , modular armour 1.0.18-41 , cofhcore 3.0.3-303
Works fine in ssp.

Server error:  http://pastebin.com/9w0gmPNX

**Comment by chbachman** [comment]
I think my Forge might be Outdated, I am going to try updating it.

**Comment by burglarnoone** [comment]
Ok hopefully it's a simple fix for you, thanks for your work on the mod.

**Comment by chbachman** [comment]
No longer being updated, sorry. Check the Readme for information.
