### ISSUE TITLE
Jetpack not working ?

### ISSUE THREAD

**Issue by KKriDD** [chbachman/ModularArmour#75]
Any issues with the jetpack ? followed all steps but it does nothing ?

**Comment by chbachman** [comment]
What issues are you having? 
Did you install the energy upgrades? 
What are the total list of upgrades?

**Comment by KKriDD** [comment]
Hi, i got on the chest :

Leadstone energy 
Hardenend energy
Reinforced energy
Jetpack

on the legs calf shields and same energy upgrades

and on the rest also same energy upgrades

further more on all pieces i got 

arthopod
lava
unblockable prot
fire
undead
magic

**Comment by chbachman** [comment]
I'm not having any problems...
What are you doing to activate it? It should be similar to creative flying.

**Comment by chbachman** [comment]
No longer being updated, sorry. Check the Readme for information.
