### ISSUE TITLE
Enhancement: Indicate required upgrade

### ISSUE THREAD

**Issue by eslachance** [chbachman/ModularArmour#84]
There is currently no indication, in the UI itself, that some upgrades require previous upgrades. For instance, placing the crafting recipe for the Resonant Upgrade gives no "clear" indication (besides the text which could be construed as "you've found a better upgrade") that all previous batteries are required.

Right now I'm trying to add night vision, and there is no indication at all that it requires anything else. Tried to put it on helmet and chest (says it's compatible everywhere) and it simply won't let me click the green checkmark. Knowing the upgrade paths via a message would be greatly helpful (until there's a book ;) )

**Comment by chbachman** [comment]
In development right now. (Hint: it's a book-ish thing)

**Comment by chbachman** [comment]
No longer being updated, sorry. Check the Readme for information.
