### ISSUE TITLE
NullPounterException when getting tablet from crafting armor in some crafting interfaces

### ISSUE THREAD

**Issue by Hazerdous** [chbachman/ModularArmour#85]
[OpenEye Report (stacktrace)](http://openeye.openmods.info/crashes/abd6a31ffe17b48da0a1d2eb44e42532)

When crafting a piece of armor for the first time (where it would give the tablet) in a Thaumcraft/Automagy crafting focus attached to a staff (possibly more tables are affected), the client crashes, and upon loading the world back up, the armor and the materials used are all missing (though, that part is probably more on Automagy's side).

Any subsequent crafts that do not trigger a tablet to be given appear to work fine.

**Comment by chbachman** [comment]
No longer being updated, sorry. Check the Readme for information.
