### ISSUE TITLE
[1.7.10][1.0.18-41] Crash on start due to missing mod(s) and invalid recipes

### ISSUE THREAD

**Issue by Aedda** [chbachman/ModularArmour#86]
If a third party mod such as Thaumcraft is installed ModularArmour creates a recipe file for it. Then if Thaumcraft is removed or disabled Minecraft can no longer start because ModularArmour is still trying to load that recipe which is now invalid and crashing with an NPE on the chbachman.api.upgrade.Recipe.toString method.

Stack trace: http://pastebin.com/0HQe6NRm

**Comment by chbachman** [comment]
Fixing now, recipes will not be loaded if the mod they require is not loaded as well. 

Sorry for the long delay, life caught up to me.
