### ISSUE TITLE
Deleting armour parts by placing them in own crafting grid

### ISSUE THREAD

**Issue by Lavode** [chbachman/ModularArmour#87]
Reproduce: 
- Right-click piece of armour to open crafting grid
- Shift-left click on same piece of armour to move it into its own grid
- See a singularity form, and watch in horror as it eats your fully upgraded armour 

Using version 1.7.10-1.0.18-41 of your mod.

**Comment by chbachman** [comment]
No longer being updated, sorry. Check the Readme for information.
