### ISSUE TITLE
[Suggestion] Galacticraft and Addons Support

### ISSUE THREAD

**Issue by Voxel-Friend** [chbachman/ModularArmour#88]
Couple Ideas how this could work.

-Thermal Insulation Tier 1: Would Require Thermal Cloth (Tier 1), uses 5 for helmet, 7 for leggings etc.

Similarly, these addons can use their respective tiers of Thermal cloth for its' upgrade.

-Thermal Insulation Tier 2:(Added by GalaxySpace) Protects from the mod's solar radiation, uses tier 2.
-Thermal Insulation Tier 2:(Added by MorePlanets) Protects from the mod's Infected Gas, uses tier 2.
-Thermal Insulation Tier 3:(Added by MorePlanets) Protects from the mod's Icy Poison, uses tier 3.
-Oxygen Upgrade: Draws from GC oxygen tanks in players inventory to allow the player to breath.
    -Could require valid GC oxygen setup.

I'm not too concerned if this suggestion gets implemented, just thought it would be interesting to code :)

**Comment by chbachman** [comment]
No longer being updated, sorry. Check the Readme for information.
