### ISSUE TITLE
Armour Upgrades

### ISSUE THREAD

**Issue by MPeti1** [chbachman/ModularArmour#89]
Hi!
I've found that mod in the FTB Horizons Daybreaker modpack,and i found a bug with the upgrade menu.When i was trying to place iron ingots into the crafting grid,it trows through the menu like when i throw it from my inventory,so i cant make upgrades to the armour.An other problem,when is crafted the armour,i got an untextured item named item.cofh.tablet.table.name (picture below),and when i open this...it has some bugs
![2016-01-17_14 34 46](https://cloud.githubusercontent.com/assets/9215491/12377735/a2618e56-bd27-11e5-831b-99717bf56520.png)
![2016-01-17_14 34 56](https://cloud.githubusercontent.com/assets/9215491/12377733/a25efc2c-bd27-11e5-92ab-4e97d078521f.png)
![2016-01-17_14 34 59](https://cloud.githubusercontent.com/assets/9215491/12377734/a260eee2-bd27-11e5-9eec-33b5dd68bc07.png)

**Comment by kjj194** [comment]
In order to craft the upgrades just turn off the NEI overlay by hitting O.

**Comment by MPeti1** [comment]
Thanks,its working now :D
