### ISSUE TITLE
Not crafting upgrades.

### ISSUE THREAD

**Issue by Pilad** [chbachman/ModularArmour#91]
If use CoFHCore-[1.7.10]3.0.3-303 all work fine.Upgrades install perfectly.
But if use CoFHCore-[1.7.10]3.1.2-325 , not working.
Fix please.

**Comment by tommydrum** [comment]
I am affected too. Also CoFH 325.

**Comment by LemADEC** [comment]
Logs or it didn't happen

**Comment by Scout91** [comment]
I am affected too. but what kind of logs are you talking about?
![modular armour bug 1](https://cloud.githubusercontent.com/assets/18028006/13982545/01417d7c-f0eb-11e5-87e9-8dd458a03d86.PNG)
![modular armour bug 2](https://cloud.githubusercontent.com/assets/18028006/13982544/0141055e-f0eb-11e5-9dad-20468854e8a6.PNG)

**Comment by LemADEC** [comment]
Client logs. Try to reproduce with only ModularArmor and latest CoFH.

**Comment by joru** [comment]
i see nothing in logs http://paste.atlauncher.com/view/0ca8ddb8
just green checkmark looks and is unclickable

**Comment by sieb** [comment]
When i am using the latest version and when i am trying to craft any upgrade it will kick me and display this log 26.04 13:30:13 [Disconnect] User sieb2 has disconnected, reason: A fatal error has occured, this connection is terminated
26.04 13:30:13 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
26.04 13:30:13 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [MinecraftServer.class:?]
26.04 13:30:13 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [MinecraftServer.class:?]
26.04 13:30:13 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
26.04 13:30:13 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013) [MinecraftServer.class:?]
26.04 13:30:13 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
26.04 13:30:13 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
26.04 13:30:13 [Server] INFO at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.46]
26.04 13:30:13 [Server] INFO at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
26.04 13:30:13 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
26.04 13:30:13 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
26.04 13:30:13 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
26.04 13:30:13 [Server] INFO at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
26.04 13:30:13 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
26.04 13:30:13 [Server] INFO at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
26.04 13:30:13 [Server] INFO at cofh.core.network.PacketHandler.decode(PacketHandler.java:40) ~[PacketHandler.class:?]
26.04 13:30:13 [Server] INFO at cofh.core.network.PacketHandler.decode(PacketHandler.java:104) ~[PacketHandler.class:?]
26.04 13:30:13 [Server] INFO at cofh.core.network.PacketCoFHBase.handleServerSide(PacketCoFHBase.java:413) ~[PacketCoFHBase.class:?]
26.04 13:30:13 [Server] INFO at chbachman.armour.network.ArmourPacket.handlePacket(ArmourPacket.java:33) ~[ArmourPacket.class:?]
26.04 13:30:13 [Server] INFO at chbachman.armour.network.ArmourPacket.handleButtonPressed(ArmourPacket.java:83) ~[ArmourPacket.class:?]
26.04 13:30:13 [Server] INFO at chbachman.armour.gui.recipe.RecipeContainer.onButtonClick(RecipeContainer.java:76) ~[RecipeContainer.class:?]
26.04 13:30:13 [Server] INFO java.lang.NoSuchMethodError: chbachman.armour.gui.crafting.ArmourContainer.func_75131_a([Lnet/minecraft/item/ItemStack;)V
26.04 13:30:13 [Server] ERROR There was a critical exception handling a packet on channel CoFH

**Comment by reydramon** [comment]
is somebody still following this because i have the same problem and cant go back to cofh 3.0.3 :/

**Comment by shadowbolt79** [comment]
I have the same issue as well.

**Comment by chbachman** [comment]
No longer being updated, sorry. Check the Readme for information.
